version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
        - /feature-.*/
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run: npm run coverage
      - run:
          name: release
          command: GH_TOKEN=$GH_TOKEN npm run semantic-release || true
